modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "GNU LGPL 3.0"

[[mods]]
modId = "explodee"
version = "${version}"
displayName = "Explodee"
authors = "KnownSH"
description = '''
Explodee is a mod that makes explosions explodee-er
'''
#logoFile = ""

[[dependencies.explodee]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.explodee]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

